[package]
name = "blog"
version = "0.1.0"
authors = ["Jose Narvaez <goyox86@gmail.com>"]

[dependencies]
diesel = "0.9.0"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"
