[package]
name = "blog"
version = "0.1.0"
authors = ["Jose Narvaez <goyox86@gmail.com>"]

[dependencies]
diesel = { version = "0.10.0", features = ["postgres"] }
diesel_codegen = { version = "0.10.0", features = ["postgres"] }
dotenv = "0.8.0"
toml = "0.2"

