#
# Database configuarion file
#

[development]
adapter = "postgresql"
encoding = "unicode"
database = "blog_development"
username = "goyox86"
password = "bailey"
host = "localhost"
port = 5432
pool = 5

[test]
adapter = "postgresql"
encoding = "unicode"
database = "blog_test"
username = "goyox86"
password = "bailey"
host = "localhost"
port = 5432
pool = 5

[production]
adapter = "postgresql"
encoding = "unicode"
database = "blog_production"
username = "goyox86"
password = "bailey"
host = "localhost"
port = 5432
pool = 5
